language: node_js
node_js:
  - "8"
  - "10"
cache:
  directories:
    - node_modules
script:
  - lerna bootstrap --loglevel=verbose
  - npm test
# https://github.com/travis-ci/travis-ci/issues/8836#issuecomment-356362524
sudo: required
before_install:
  - sudo apt-get update
  - sudo apt-get install graphicsmagick
