language: node_js
node_js:
  - "8.9.4"
  - "9"
dist: trusty
env:
  - DISABLE_CHROMIUM_SANDBOX=true
addons:
  chrome: stable
sudo: required
cache:
  directories:
    - node_modules
script:
  - lerna bootstrap
  - npm test
